# Generated by Django 5.2 on 2025-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
