# Generated by Django 5.1.6 on 2025-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('lien', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_pub', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
