# Generated by Django 5.1.6 on 2025-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
