# Generated by Django 5.1.6 on 2025-04-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
