# Generated by Django 5.1.6 on 2025-04-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_img_url_article_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_pub',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
