# Generated by Django 5.1.6 on 2025-04-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_article_date_pub_remove_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
    ]
